name: cb
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - numpy
  - pandas
  - ipykernel 
  - ipywidgets
  - dash
  - matplotlib
  - pip
  - pip:
    - plotly
    - chart_studio 
    - dash_bootstrap_components

